# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collectionID', models.IntegerField(primary_key=True, serialize=False)),
                ('collectionName', models.CharField(max_length=50)),
                ('collectionDescription', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plantID', models.IntegerField(primary_key=True, serialize=False)),
                ('sciName', models.CharField(max_length=50)),
                ('genName', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=400)),
                ('imageURL', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlantCollection',
            fields=[
                ('plantCollectionID', models.IntegerField(primary_key=True, serialize=False)),
                ('collectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.Collection')),
                ('plantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.Plant')),
            ],
        ),
    ]
