# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-19 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collectionID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plantID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plantcollection',
            name='plantCollectionID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
